# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "aCejE8R4T1jKxe91NCXnxSnnYfJGP0lLQf3p42zpekrZoTunmbjVwvXGvUxNsVWmwoaTCs43OYjmlYu5MH3o7QpnclbrAda4CtDtRoxJWABvXeDuJruY0CQ1LBv2J7S2pirYPgIW+YzXo60G6j1sTX7YUNogDsLobVamlmP0t3CB7jrznPQYlb8XBf0S/ia+7sPGaVhc0NESk18AQW1NZutJNdl914WeptVbibCs5TLlBNlaif6gTJ7BmxoDQ7lLbvX5Alq9yt7JhoWB+StdbtjxPXXgdJK61z/00GhYqcoE7+F9m1GuELw/wAIfA7miuxIYYkpaRUX8TQG/SWnlAto0YEM0Yu48mpWT8zui+UumR/HM2MlRMAp2Qk1epAxdIFuZo6ZjU7impWoDxChGTqyMceOkiwhp2P3LMVRqSMTjjPIDuvvF0wV2nmF4bB3Kmw9xAMVJRDncRsazfj6GxHBWBEilf/BX6o6FqeH16j8s+s2U/Z2chwvxN/9iDnCFR4Ya29hnUnuVG8hRfvBY19MBYdyqPWS5o7jKmsvoHTx7Gy4Hvg6vZ5O8yIBnKRRC1sMWIIm5H3bqfr3V0qeB+s9Gs3JrCm4K9cR1WblSJ4kckESxdy/jji3PuGO28AtBdLWEDgNQZhnglYUuuk8/FuC8BDj3hYinPROgUAFyTL4="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
