travis:
  secure:
    BINSTAR_TOKEN: CB6RwLXTBZjc3zdFn1eT7rgm3kwLSjisgFnV046yvU9yM5GftlyhNVYvZjgIuzv+pUpcPw4abhksX4XeLYXY4vYJTDMpURnBbty6eBRhnIF0PkYpv8gNQvPMMu4Do0Vxoms+WlOuscFXCuwiXlY1cMCuoy7S+3JYpUk19S5KPJVaBs47bv130iD5Q5VKGeYga2BDikQYKa3mUf8yqHxD4zZI/tG2xSD7dAqvC1iUrlMxcaPPZEY2g9NLRBG2sXTD69pFSo8hByryouff/pe6h8w6RE4tpsLsCHsGxtpzKXJpN7AM9V8WbT2ZUEfjv1L2GR5vGgEC3y86fcMHawHNG3aAurcJBatxkW5I9PJXhM/mni6U/6WOnm/V3m3udS8M4qyimbTVPcJeQwzKdTNwOLa2yYvMdN6mVzx8x3dAtsiZDNPb0jbIDMFf6IRpxcR/HeqWPwgE6AyPG0bL2bgSujgPPN5ERGAdHiUf52ER5DC6zMuNJPxLWVpi//mAZmE7lF+qgycqPLwNoggykiM9qHBiC74gbIfO9ZMeulW9hQ0PZ8X+pdt4f2innSnrwLc2Djs3ONxRt8yOS4r5RyTsVesmFvBh9xcso1YjuMd+Kc9euCZOUfzyM/3YTZ0VOJbOKrQ1DZEe2jvuVKHGHQakzJTt2yvyn4ZoZXrDF7dflCw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
