travis:
  secure:
    BINSTAR_TOKEN: aCejE8R4T1jKxe91NCXnxSnnYfJGP0lLQf3p42zpekrZoTunmbjVwvXGvUxNsVWmwoaTCs43OYjmlYu5MH3o7QpnclbrAda4CtDtRoxJWABvXeDuJruY0CQ1LBv2J7S2pirYPgIW+YzXo60G6j1sTX7YUNogDsLobVamlmP0t3CB7jrznPQYlb8XBf0S/ia+7sPGaVhc0NESk18AQW1NZutJNdl914WeptVbibCs5TLlBNlaif6gTJ7BmxoDQ7lLbvX5Alq9yt7JhoWB+StdbtjxPXXgdJK61z/00GhYqcoE7+F9m1GuELw/wAIfA7miuxIYYkpaRUX8TQG/SWnlAto0YEM0Yu48mpWT8zui+UumR/HM2MlRMAp2Qk1epAxdIFuZo6ZjU7impWoDxChGTqyMceOkiwhp2P3LMVRqSMTjjPIDuvvF0wV2nmF4bB3Kmw9xAMVJRDncRsazfj6GxHBWBEilf/BX6o6FqeH16j8s+s2U/Z2chwvxN/9iDnCFR4Ya29hnUnuVG8hRfvBY19MBYdyqPWS5o7jKmsvoHTx7Gy4Hvg6vZ5O8yIBnKRRC1sMWIIm5H3bqfr3V0qeB+s9Gs3JrCm4K9cR1WblSJ4kckESxdy/jji3PuGO28AtBdLWEDgNQZhnglYUuuk8/FuC8BDj3hYinPROgUAFyTL4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
